# Generated by Django 5.0.6 on 2026-07-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_employe_7236fb_idx',
            old_name='leaves_leav_employe_1e1234_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leaves_leav_start_d_96457d_idx',
            old_name='leaves_leav_start_d_2a5678_idx',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('UNPAID', 'Unpaid Leave')], default='ANNUAL', max_length=10),
        ),
    ]
